version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Ejecutando script de procesamiento..."
      - python3 procesar.py
  post_build:
    commands:
      - echo "Validando archivo generado..."
      - if [ -f resultado.txt ]; then echo "Validacion exitosa"; else echo "Error: Archivo no generado" && exit 1; fi
artifacts:
  files:
    - '**/*'