version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Ejecutando el script de procesamiento..."
      - [cite_start]python3 procesar.py [cite: 8, 28]
  post_build:
    commands:
      - echo "Validando que el archivo resultado.txt fue generado correctamente..."
      - test -f resultado.txt && echo "Archivo encontrado" || (echo "Error: resultado.txt no existe" && exit 1) [cite_start][cite: 9, 29]

artifacts:
  files:
    - '**/*'