version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Ejecutando el script..."
      - python3 procesar.py
  post_build:
    commands:
      - echo "Validando resultado.txt..."
      - ls -l resultado.txt
      - test -f resultado.txt
artifacts:
  files:
    - '**/* '